print('Hello, world!')
print('hey this is leo and i am starting learning python this is my first python code and will continue to learn')
print("1")
print('hey hey why hey hey hey hey hey hey hey hey')
print("print run")
print("having the same feeling as when i was learning java for the first time but that was hectic and this is smooth but thathasanother level of understanding ")